### ISSUE TITLE
apply to datatables

### ISSUE THREAD

**Issue by ibnubay** [monnierj/django-datatables-server-side#1]
Can u give an example how to apply your Class on template html with datatables configurations ?

My datatables config is:
```
$('.datatable-scroll-x-fixed-both').DataTable({
                ajax: '{% url 'users:user_json_view' %}',
                serverSide: true,
                scrollX: true
            });
```

**Comment by monnierj** [comment]
Well, the view that matches the 'users:user_json_view' URL must be a subclass of DatatablesServerSideView, with the right parameters set (as shown on the project description), and your DataTables should get your data in the right format.
