### ISSUE TITLE
Suggested Features for Django 3.x integration

### ISSUE THREAD

**Issue by abedyngash** [monnierj/django-datatables-server-side#6]
For anyone who lands here, This works awesome even in Django 3.0 with the exception of a simple import:

```from django.utils import six```

Should change to:
```pip install six``` > ```import six```

Also in a case where you want to have ```all records``` in the ```lengthMenu```, according to the [Documentation](https://datatables.net/reference/option/lengthMenu), I thought changing this part to be worthwhile:

```paginator = Paginator(qs, params['length'])```

to:
```
if params['length'] > 0:
    paginator = Paginator(qs, params['length'])
else:
    paginator = Paginator(qs, self.model.objects.all().count())
```
Within the views.
I would open a pull request but again this repo seems not to be under maintenance.

**Comment by monnierj** [comment]
Hi,

Thanks for your feedback, and sorry for the complete lack of response.

I'm pulling the plug on this project since I'm not using Django or Datatables anymore, but feel free to make a fork if it's useful to you.
